Fix with old nixpkgs
Attempting to use the current ghc.nix to build an old version of GHC
(`ghc-9.7-start`) produces errors:

```
| Run GhcPkg Update (Stage0 InTreeLibs): _build/stage0/libraries/ghc-boot-th/inplace-pkg-config => none
dieVerbatim: user error (Error: hadrian:
'/nix/store/3dahn98q1m46ickndsg797zp8gv801b2-ghc-9.6.6-with-packages/bin/ghc'
exited with an error:
ghc-9.6.6: can't find a package database at
_build/stage0/libraries/ghc-boot-th/build/package.conf.inplace
)
Build failed.
```

I believe this error is due to using a too-new version of Cabal.
Currently, nixpkgs only includes Cabal 3.12, which is 2-3 releases too
new for `ghc-9.7-start`. Using an old version of nixpkgs [1] with
ghc.nix also errors:

```
error: undefined variable 'happy'
at /nix/store/g8fnx3r5jccwgwhiridj6rlmqwd80cmi-source/ghc.nix:270:20:
   269|     export GHCPKG=$NIX_GHCPKG
   270|     export HAPPY=${happy}/bin/happy
      |                    ^
   271|     export ALEX=${alex}/bin/alex
```

Using `hspkgs.happy` instead of `happy` (which defers to `pkgs.happy`
due to the `with pkgs;` clause on line 85 fixes this.

[1]: https://github.com/nixos/nixpkgs/commit/012700eae502f6054a056cf7b94f78ff549e278d